export const Icons = [
  {
    id: "step-backward",
    name: "Step Backward",
    category: "direction",
    unicode: "e601",
    version: "3.7.3",
  },
  {
    id: "step-forward",
    name: "Step Forward",
    category: "direction",
    unicode: "e600",
    version: "3.7.3",
  },
  {
    id: "fast-backward",
    name: "Fast Backward",
    category: "direction",
    unicode: "e6c6",
    version: "3.7.3",
  },
  {
    id: "fast-forward",
    name: "Fast Forward",
    category: "direction",
    unicode: "e6c7",
    version: "3.7.3",
  },
  {
    id: "shrink",
    name: "Shrink",
    category: "direction",
    unicode: "e614",
    version: "3.7.3",
  },
  {
    id: "arrows-alt",
    name: "Arrows Alt",
    category: "direction",
    unicode: "e615",
    version: "3.7.3",
  },
  {
    id: "down",
    name: "Down",
    category: "direction",
    unicode: "e61d",
    version: "3.7.3",
  },
  {
    id: "up",
    name: "Up",
    category: "direction",
    unicode: "e61e",
    version: "3.7.3",
  },
  {
    id: "left",
    name: "Left",
    category: "direction",
    unicode: "e620",
    version: "3.7.3",
  },
  {
    id: "right",
    name: "Right",
    category: "direction",
    unicode: "e61f",
    version: "3.7.3",
  },
  {
    id: "caret-up",
    name: "Caret Up",
    category: "direction",
    unicode: "e607",
    version: "3.7.3",
  },
  {
    id: "caret-down",
    name: "Caret Down",
    category: "direction",
    unicode: "e606",
    version: "3.7.3",
  },
  {
    id: "caret-left",
    name: "Caret Left",
    category: "direction",
    unicode: "e605",
    version: "3.7.3",
  },
  {
    id: "caret-right",
    name: "Caret Right",
    category: "direction",
    unicode: "e604",
    version: "3.7.3",
  },
  {
    id: "up-circle",
    name: "Up Circle",
    category: "direction",
    unicode: "e60a",
    version: "3.7.3",
  },
  {
    id: "down-circle",
    name: "Down Circle",
    category: "direction",
    unicode: "e60b",
    version: "3.7.3",
  },
  {
    id: "left-circle",
    name: "Left Circle",
    category: "direction",
    unicode: "e609",
    version: "3.7.3",
  },
  {
    id: "right-circle",
    name: "Right Circle",
    category: "direction",
    unicode: "e608",
    version: "3.7.3",
  },
  {
    id: "up-circle-o",
    name: "Up Circle Outlined",
    category: "direction",
    unicode: "e60e",
    version: "3.7.3",
  },
  {
    id: "down-circle-o",
    name: "Down Circle Outlined",
    category: "direction",
    unicode: "e60f",
    version: "3.7.3",
  },
  {
    id: "right-circle-o",
    name: "Right Circle Outlined",
    category: "direction",
    unicode: "e60c",
    version: "3.7.3",
  },
  {
    id: "left-circle-o",
    name: "Left Circle Outlined",
    category: "direction",
    unicode: "e60d",
    version: "3.7.3",
  },
  {
    id: "double-right",
    name: "Double Right",
    category: "direction",
    unicode: "e617",
    version: "3.7.3",
  },
  {
    id: "double-left",
    name: "Double Left",
    category: "direction",
    unicode: "e618",
    version: "3.7.3",
  },
  {
    id: "verticle-left",
    name: "Verticle Left",
    category: "direction",
    unicode: "e610",
    version: "3.7.3",
  },
  {
    id: "verticle-right",
    name: "Verticle Right",
    category: "direction",
    unicode: "e611",
    version: "3.7.3",
  },
  {
    id: "forward",
    name: "Forward",
    category: "direction",
    unicode: "e602",
    version: "3.7.3",
  },
  {
    id: "backward",
    name: "Backward",
    category: "direction",
    unicode: "e603",
    version: "3.7.3",
  },
  {
    id: "rollback",
    name: "Rollback",
    category: "direction",
    unicode: "e612",
    version: "3.7.3",
  },
  {
    id: "enter",
    name: "Enter",
    category: "direction",
    unicode: "e6a0",
    version: "3.7.3",
  },
  {
    id: "retweet",
    name: "Retweet",
    category: "direction",
    unicode: "e613",
    version: "3.7.3",
  },
  {
    id: "swap",
    name: "Swap",
    category: "direction",
    unicode: "e642",
    version: "3.7.3",
  },
  {
    id: "swap-left",
    name: "Swap Left",
    category: "direction",
    unicode: "e643",
    version: "3.7.3",
  },
  {
    id: "swap-right",
    name: "Swap Right",
    category: "direction",
    unicode: "e644",
    version: "3.7.3",
  },
  {
    id: "arrow-up",
    name: "Arrow Up",
    category: "direction",
    unicode: "e61a",
    version: "3.7.3",
  },
  {
    id: "arrow-down",
    name: "Arrow Down",
    category: "direction",
    unicode: "e619",
    version: "3.7.3",
  },
  {
    id: "arrow-left",
    name: "Arrow Left",
    category: "direction",
    unicode: "e61c",
    version: "3.7.3",
  },
  {
    id: "arrow-right",
    name: "Arrow Right",
    category: "direction",
    unicode: "e61b",
    version: "3.7.3",
  },
  {
    id: "play-circle",
    name: "Play Circle",
    category: "direction",
    unicode: "e6d0",
    version: "3.7.3",
  },
  {
    id: "play-circle-o",
    name: "Play Circle Outlined",
    category: "direction",
    unicode: "e6d1",
    version: "3.7.3",
  },
  {
    id: "up-square",
    name: "Up Square",
    category: "direction",
    unicode: "e6c8",
    version: "3.7.3",
  },
  {
    id: "down-square",
    name: "Down Square",
    category: "direction",
    unicode: "e6c9",
    version: "3.7.3",
  },
  {
    id: "left-square",
    name: "Left Square",
    category: "direction",
    unicode: "e6ca",
    version: "3.7.3",
  },
  {
    id: "right-square",
    name: "Right Square",
    category: "direction",
    unicode: "e6cb",
    version: "3.7.3",
  },
  {
    id: "up-square-o",
    name: "Up Square Outlined",
    category: "direction",
    unicode: "e6cf",
    version: "3.7.3",
  },
  {
    id: "down-square-o",
    name: "Down Square Outlined",
    category: "direction",
    unicode: "e6ce",
    version: "3.7.3",
  },
  {
    id: "left-square-o",
    name: "Left Square Outlined",
    category: "direction",
    unicode: "e6cd",
    version: "3.7.3",
  },
  {
    id: "right-square-o",
    name: "Right Square Outlined",
    category: "direction",
    unicode: "e6cc",
    version: "3.7.3",
  },
  {
    id: "login",
    name: "Login",
    category: "direction",
    unicode: "e657",
    version: "3.7.3",
  },
  {
    id: "logout",
    name: "Logout",
    category: "direction",
    unicode: "e65a",
    version: "3.7.3",
  },
  {
    id: "menu-fold",
    name: "Menu Fold",
    category: "direction",
    unicode: "e9ac",
    version: "3.7.3",
  },
  {
    id: "menu-unfold",
    name: "Menu Unfold",
    category: "direction",
    unicode: "e9ad",
    version: "3.7.3",
  },
  {
    id: "question",
    name: "Question",
    category: "suggestion",
    unicode: "e63a",
    version: "3.7.3",
  },
  {
    id: "question-circle-o",
    name: "Question Circle Outlined",
    category: "suggestion",
    unicode: "e63c",
    version: "3.7.3",
  },
  {
    id: "question-circle",
    name: "Question Circle",
    category: "suggestion",
    unicode: "e63b",
    version: "3.7.3",
  },
  {
    id: "plus",
    name: "Plus",
    category: "suggestion",
    unicode: "e627",
    version: "3.7.3",
  },
  {
    id: "plus-circle-o",
    name: "Plus Circle Outlined",
    category: "suggestion",
    unicode: "e625",
    version: "3.7.3",
  },
  {
    id: "plus-circle",
    name: "Plus Circle",
    category: "suggestion",
    unicode: "e626",
    version: "3.7.3",
  },
  {
    id: "pause",
    name: "Pause",
    category: "suggestion",
    unicode: "e63d",
    version: "3.7.3",
  },
  {
    id: "pause-circle-o",
    name: "Pause Circle Outlined",
    category: "suggestion",
    unicode: "e63f",
    version: "3.7.3",
  },
  {
    id: "pause-circle",
    name: "Pause Circle",
    category: "suggestion",
    unicode: "e63e",
    version: "3.7.3",
  },
  {
    id: "minus",
    name: "Minus",
    category: "suggestion",
    unicode: "e624",
    version: "3.7.3",
  },
  {
    id: "minus-circle-o",
    name: "Minus Circle Outlined",
    category: "suggestion",
    unicode: "e623",
    version: "3.7.3",
  },
  {
    id: "minus-circle",
    name: "Minus Circle",
    category: "suggestion",
    unicode: "e622",
    version: "3.7.3",
  },
  {
    id: "plus-square",
    name: "Plus Square",
    category: "suggestion",
    unicode: "e6c0",
    version: "3.7.3",
  },
  {
    id: "plus-square-o",
    name: "Plus Square Outlined",
    category: "suggestion",
    unicode: "e645",
    version: "3.7.3",
  },
  {
    id: "minus-square",
    name: "Minus Square",
    category: "suggestion",
    unicode: "e6c1",
    version: "3.7.3",
  },
  {
    id: "minus-square-o",
    name: "Minus Square Outlined",
    category: "suggestion",
    unicode: "e621",
    version: "3.7.3",
  },
  {
    id: "info",
    name: "Info",
    category: "suggestion",
    unicode: "e62a",
    version: "3.7.3",
  },
  {
    id: "info-circle-o",
    name: "Info Circle Outlined",
    category: "suggestion",
    unicode: "e629",
    version: "3.7.3",
  },
  {
    id: "info-circle",
    name: "Info Circle",
    category: "suggestion",
    unicode: "e628",
    version: "3.7.3",
  },
  {
    id: "exclamation",
    name: "Exclamation",
    category: "suggestion",
    unicode: "e62b",
    version: "3.7.3",
  },
  {
    id: "exclamation-circle-o",
    name: "Exclamation Circle Outlined",
    category: "suggestion",
    unicode: "e62d",
    version: "3.7.3",
  },
  {
    id: "exclamation-circle",
    name: "Exclamation Circle",
    category: "suggestion",
    unicode: "e62c",
    version: "3.7.3",
  },
  {
    id: "close",
    name: "Close",
    category: "suggestion",
    unicode: "e633",
    version: "3.7.3",
  },
  {
    id: "close-circle",
    name: "Close Circle",
    category: "suggestion",
    unicode: "e62e",
    version: "3.7.3",
  },
  {
    id: "close-circle-o",
    name: "Close Circle Outlined",
    category: "suggestion",
    unicode: "e62f",
    version: "3.7.3",
  },
  {
    id: "close-square",
    name: "Close Square",
    category: "suggestion",
    unicode: "e6c2",
    version: "3.7.3",
  },
  {
    id: "close-square-o",
    name: "Close Square Outlined",
    category: "suggestion",
    unicode: "e6c3",
    version: "3.7.3",
  },
  {
    id: "check",
    name: "Check",
    category: "suggestion",
    unicode: "e632",
    version: "3.7.3",
  },
  {
    id: "check-circle",
    name: "Check Circle",
    category: "suggestion",
    unicode: "e630",
    version: "3.7.3",
  },
  {
    id: "check-circle-o",
    name: "Check Circle Outlined",
    category: "suggestion",
    unicode: "e631",
    version: "3.7.3",
  },
  {
    id: "check-square",
    name: "Check Square",
    category: "suggestion",
    unicode: "e6c4",
    version: "3.7.3",
  },
  {
    id: "check-square-o",
    name: "Check Square Outlined",
    category: "suggestion",
    unicode: "e6c5",
    version: "3.7.3",
  },
  {
    id: "clock-circle-o",
    name: "Clock Circle Outlined",
    category: "suggestion",
    unicode: "e641",
    version: "3.7.3",
  },
  {
    id: "clock-circle",
    name: "Clock Circle",
    category: "suggestion",
    unicode: "e640",
    version: "3.7.3",
  },
  {
    id: "warning",
    name: "Warning",
    category: "suggestion",
    unicode: "e997",
    version: "3.7.3",
  },
  {
    id: "android",
    name: "Android",
    category: "logo",
    unicode: "e938",
    version: "3.7.3",
  },
  {
    id: "android-o",
    name: "Android Outlined",
    category: "logo",
    unicode: "e68d",
    version: "3.7.3",
  },
  {
    id: "apple",
    name: "Apple",
    category: "logo",
    unicode: "e68c",
    version: "3.7.3",
  },
  {
    id: "apple-o",
    name: "Apple Outlined",
    category: "logo",
    unicode: "e6d4",
    version: "3.7.3",
  },
  {
    id: "windows",
    name: "Windows",
    category: "logo",
    unicode: "e68b",
    version: "3.7.3",
  },
  {
    id: "windows-o",
    name: "Windows Outlined",
    category: "logo",
    unicode: "e6bc",
    version: "3.7.3",
  },
  {
    id: "ie",
    name: "IE",
    category: "logo",
    unicode: "e69b",
    version: "3.7.3",
  },
  {
    id: "chrome",
    name: "Chrome",
    category: "logo",
    unicode: "e6ac",
    version: "3.7.3",
  },
  {
    id: "github",
    name: "GitHub",
    category: "logo",
    unicode: "e6ad",
    version: "3.7.3",
  },
  {
    id: "aliwangwang",
    name: "Aliwangwang",
    category: "logo",
    unicode: "e68e",
    version: "3.7.3",
  },
  {
    id: "aliwangwang-o",
    name: "Aliwangwang Outlined",
    category: "logo",
    unicode: "e68f",
    version: "3.7.3",
  },
  {
    id: "dingding",
    name: "Dingding",
    category: "logo",
    unicode: "e923",
    version: "3.7.3",
  },
  {
    id: "dingding-o",
    name: "Dingding Outlined",
    category: "logo",
    unicode: "e925",
    version: "3.7.3",
  },
  {
    id: "weibo-square",
    name: "Weibo Square",
    category: "logo",
    unicode: "e6f5",
    version: "3.7.3",
  },
  {
    id: "weibo-circle",
    name: "Weibo Circle",
    category: "logo",
    unicode: "e6f4",
    version: "3.7.3",
  },
  {
    id: "taobao-circle",
    name: "Taobao Circle",
    category: "logo",
    unicode: "e6f3",
    version: "3.7.3",
  },
  {
    id: "html5",
    name: "HTML5",
    category: "logo",
    unicode: "e9c7",
    version: "3.7.3",
  },
  {
    id: "weibo",
    name: "Weibo",
    category: "logo",
    unicode: "e9c6",
    version: "3.7.3",
  },
  {
    id: "twitter",
    name: "Twitter",
    category: "logo",
    unicode: "e9c5",
    version: "3.7.3",
  },
  {
    id: "wechat",
    name: "Wechat",
    category: "logo",
    unicode: "e9c4",
    version: "3.7.3",
  },
  {
    id: "youtube",
    name: "Youtube",
    category: "logo",
    unicode: "e9c3",
    version: "3.7.3",
  },
  {
    id: "alipay-circle",
    name: "Alipay Circle",
    category: "logo",
    unicode: "e9c2",
    version: "3.7.3",
  },
  {
    id: "taobao",
    name: "Taobao",
    category: "logo",
    unicode: "e9c1",
    version: "3.7.3",
  },
  {
    id: "skype",
    name: "Skype",
    category: "logo",
    unicode: "e9c0",
    version: "3.7.3",
  },
  {
    id: "qq",
    name: "QQ",
    category: "logo",
    unicode: "e9bf",
    version: "3.7.3",
  },
  {
    id: "medium-workmark",
    name: "Medium Workmark",
    category: "logo",
    unicode: "e9be",
    version: "3.7.3",
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "logo",
    unicode: "e9bd",
    version: "3.7.3",
  },
  {
    id: "medium",
    name: "Medium",
    category: "logo",
    unicode: "e9bc",
    version: "3.7.3",
  },
  {
    id: "linkedin",
    name: "Linkedin",
    category: "logo",
    unicode: "e9bb",
    version: "3.7.3",
  },
  {
    id: "google-plus",
    name: "Google Plus",
    category: "logo",
    unicode: "e9ba",
    version: "3.7.3",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    category: "logo",
    unicode: "e9b9",
    version: "3.7.3",
  },
  {
    id: "facebook",
    name: "Facebook",
    category: "logo",
    unicode: "e9b8",
    version: "3.7.3",
  },
  {
    id: "codepen",
    name: "Codepen",
    category: "logo",
    unicode: "e9b7",
    version: "3.7.3",
  },
  {
    id: "amazon",
    name: "Amazon",
    category: "logo",
    unicode: "e9b6",
    version: "3.7.3",
  },
  {
    id: "google",
    name: "Google",
    category: "logo",
    unicode: "e9b5",
    version: "3.7.3",
  },
  {
    id: "codepen-circle",
    name: "Codepen Circle",
    category: "logo",
    unicode: "e9b4",
    version: "3.7.3",
  },
  {
    id: "alipay",
    name: "Alipay",
    category: "logo",
    unicode: "e9b3",
    version: "3.7.3",
  },
  {
    id: "ant-design",
    name: "Ant Design",
    category: "logo",
    unicode: "e9b2",
    version: "3.7.3",
  },
  {
    id: "aliyun",
    name: "Aliyun",
    category: "logo",
    unicode: "e9f4",
    version: "3.7.3",
  },
  {
    id: "zhihu",
    name: "Zhihu",
    category: "logo",
    unicode: "e703",
    version: "3.7.3",
  },
  {
    id: "slack",
    name: "Slack",
    category: "logo",
    unicode: "e705",
    version: "3.7.3",
  },
  {
    id: "slack-square",
    name: "Slack Square",
    category: "logo",
    unicode: "e706",
    version: "3.7.3",
  },
  {
    id: "behance",
    name: "Behance",
    category: "logo",
    unicode: "e707",
    version: "3.7.3",
  },
  {
    id: "behance-square",
    name: "Behance Square",
    category: "logo",
    unicode: "e708",
    version: "3.7.3",
  },
  {
    id: "dribbble",
    name: "Dribbble",
    category: "logo",
    unicode: "e709",
    version: "3.7.3",
  },
  {
    id: "dribbble-square",
    name: "Dribbble Square",
    category: "logo",
    unicode: "e70a",
    version: "3.7.3",
  },
  {
    id: "instagram",
    name: "Instagram",
    category: "logo",
    unicode: "e70b",
    version: "3.7.3",
  },
  {
    id: "yuque",
    name: "Yuque",
    category: "logo",
    unicode: "e70c",
    version: "3.7.3",
  },
  {
    id: "lock",
    name: "Lock",
    category: "other",
    unicode: "e67b",
    version: "3.7.3",
  },
  {
    id: "unlock",
    name: "Unlock",
    category: "other",
    unicode: "e6ba",
    version: "3.7.3",
  },
  {
    id: "area-chart",
    name: "Area Chart",
    category: "other",
    unicode: "e65c",
    version: "3.7.3",
  },
  {
    id: "pie-chart",
    name: "Pie Chart",
    category: "other",
    unicode: "e6b8",
    version: "3.7.3",
  },
  {
    id: "bar-chart",
    name: "Bar Chart",
    category: "other",
    unicode: "e6be",
    version: "3.7.3",
  },
  {
    id: "dot-chart",
    name: "Dot Chart",
    category: "other",
    unicode: "e6bd",
    version: "3.7.3",
  },
  {
    id: "bars",
    name: "Bars",
    category: "other",
    unicode: "e639",
    version: "3.7.3",
  },
  {
    id: "book",
    name: "Book",
    category: "other",
    unicode: "e637",
    version: "3.7.3",
  },
  {
    id: "calendar",
    name: "Calendar",
    category: "other",
    unicode: "e6bb",
    version: "3.7.3",
  },
  {
    id: "cloud",
    name: "Cloud",
    category: "other",
    unicode: "e680",
    version: "3.7.3",
  },
  {
    id: "cloud-download",
    name: "Cloud Download",
    category: "other",
    unicode: "e682",
    version: "3.7.3",
  },
  {
    id: "code",
    name: "Code",
    category: "other",
    unicode: "e6bf",
    version: "3.7.3",
  },
  {
    id: "code-o",
    name: "Code Outlined",
    category: "other",
    unicode: "e636",
    version: "3.7.3",
  },
  {
    id: "copy",
    name: "Copy",
    category: "other",
    unicode: "e648",
    version: "3.7.3",
  },
  {
    id: "credit-card",
    name: "Credit Card",
    category: "other",
    unicode: "e635",
    version: "3.7.3",
  },
  {
    id: "delete",
    name: "Delete",
    category: "other",
    unicode: "e69f",
    version: "3.7.3",
  },
  {
    id: "desktop",
    name: "Desktop",
    category: "other",
    unicode: "e6b4",
    version: "3.7.3",
  },
  {
    id: "download",
    name: "Download",
    category: "other",
    unicode: "e6b7",
    version: "3.7.3",
  },
  {
    id: "edit",
    name: "Edit",
    category: "other",
    unicode: "e692",
    version: "3.7.3",
  },
  {
    id: "ellipsis",
    name: "Ellipsis",
    category: "other",
    unicode: "e647",
    version: "3.7.3",
  },
  {
    id: "file",
    name: "File",
    category: "other",
    unicode: "e664",
    version: "3.7.3",
  },
  {
    id: "file-text",
    name: "File Text",
    category: "other",
    unicode: "e698",
    version: "3.7.3",
  },
  {
    id: "file-unknown",
    name: "File Unknown",
    category: "other",
    unicode: "e6af",
    version: "3.7.3",
  },
  {
    id: "file-pdf",
    name: "File PDF",
    category: "other",
    unicode: "e6b3",
    version: "3.7.3",
  },
  {
    id: "file-word",
    name: "File Word",
    category: "other",
    unicode: "e6b2",
    version: "3.7.3",
  },
  {
    id: "file-excel",
    name: "File Excel",
    category: "other",
    unicode: "e6b0",
    version: "3.7.3",
  },
  {
    id: "file-jpg",
    name: "File JPG",
    category: "other",
    unicode: "e69c",
    version: "3.7.3",
  },
  {
    id: "file-ppt",
    name: "File PPT",
    category: "other",
    unicode: "e6b1",
    version: "3.7.3",
  },
  {
    id: "file-markdown",
    name: "File Markdown",
    category: "other",
    unicode: "e704",
    version: "3.7.3",
  },
  {
    id: "file-add",
    name: "File Add",
    category: "other",
    unicode: "e910",
    version: "3.7.3",
  },
  {
    id: "folder",
    name: "Folder",
    category: "other",
    unicode: "e662",
    version: "3.7.3",
  },
  {
    id: "folder-open",
    name: "Folder Open",
    category: "other",
    unicode: "e699",
    version: "3.7.3",
  },
  {
    id: "folder-add",
    name: "Folder Add",
    category: "other",
    unicode: "e914",
    version: "3.7.3",
  },
  {
    id: "hdd",
    name: "Hard Disk Drive",
    category: "other",
    unicode: "e69a",
    version: "3.7.3",
  },
  {
    id: "frown",
    name: "Frown",
    category: "other",
    unicode: "e646",
    version: "3.7.3",
  },
  {
    id: "frown-o",
    name: "Frown Outlined",
    category: "other",
    unicode: "e6a9",
    version: "3.7.3",
  },
  {
    id: "meh",
    name: "Meh",
    category: "other",
    unicode: "e666",
    version: "3.7.3",
  },
  {
    id: "meh-o",
    name: "Meh Outlined",
    category: "other",
    unicode: "e667",
    version: "3.7.3",
  },
  {
    id: "smile",
    name: "Smile",
    category: "other",
    unicode: "e6a7",
    version: "3.7.3",
  },
  {
    id: "smile-o",
    name: "Smile Outlined",
    category: "other",
    unicode: "e6a8",
    version: "3.7.3",
  },
  {
    id: "inbox",
    name: "Inbox",
    category: "other",
    unicode: "e67a",
    version: "3.7.3",
  },
  {
    id: "laptop",
    name: "Laptop",
    category: "other",
    unicode: "e65f",
    version: "3.7.3",
  },
  {
    id: "appstore-o",
    name: "App Store Outlined",
    category: "other",
    unicode: "e695",
    version: "3.7.3",
  },
  {
    id: "appstore",
    name: "App Store",
    category: "other",
    unicode: "e696",
    version: "3.7.3",
  },
  {
    id: "line-chart",
    name: "Line Chart",
    category: "other",
    unicode: "e65d",
    version: "3.7.3",
  },
  {
    id: "link",
    name: "Link",
    category: "other",
    unicode: "e65b",
    version: "3.7.3",
  },
  {
    id: "mail",
    name: "Mail",
    category: "other",
    unicode: "e659",
    version: "3.7.3",
  },
  {
    id: "mobile",
    name: "Mobile",
    category: "other",
    unicode: "e678",
    version: "3.7.3",
  },
  {
    id: "notification",
    name: "Notification",
    category: "other",
    unicode: "e677",
    version: "3.7.3",
  },
  {
    id: "paper-clip",
    name: "Paper Clip",
    category: "other",
    unicode: "e676",
    version: "3.7.3",
  },
  {
    id: "picture",
    name: "Picture",
    category: "other",
    unicode: "e674",
    version: "3.7.3",
  },
  {
    id: "poweroff",
    name: "Poweroff",
    category: "other",
    unicode: "e6d5",
    version: "3.7.3",
  },
  {
    id: "reload",
    name: "Reload",
    category: "other",
    unicode: "e616",
    version: "3.7.3",
  },
  {
    id: "search",
    name: "Search",
    category: "other",
    unicode: "e670",
    version: "3.7.3",
  },
  {
    id: "setting",
    name: "Setting",
    category: "other",
    unicode: "e672",
    version: "3.7.3",
  },
  {
    id: "share-alt",
    name: "Share Alt",
    category: "other",
    unicode: "e671",
    version: "3.7.3",
  },
  {
    id: "shopping-cart",
    name: "Shopping Cart",
    category: "other",
    unicode: "e668",
    version: "3.7.3",
  },
  {
    id: "tablet",
    name: "Tablet",
    category: "other",
    unicode: "e66e",
    version: "3.7.3",
  },
  {
    id: "tag",
    name: "Tag",
    category: "other",
    unicode: "e6d2",
    version: "3.7.3",
  },
  {
    id: "tag-o",
    name: "Tag Outlined",
    category: "other",
    unicode: "e6d3",
    version: "3.7.3",
  },
  {
    id: "tags",
    name: "Tags",
    category: "other",
    unicode: "e67d",
    version: "3.7.3",
  },
  {
    id: "tags-o",
    name: "Tags Outlined",
    category: "other",
    unicode: "e67e",
    version: "3.7.3",
  },
  {
    id: "to-top",
    name: "To Top",
    category: "other",
    unicode: "e66c",
    version: "3.7.3",
  },
  {
    id: "upload",
    name: "Upload",
    category: "other",
    unicode: "e6b6",
    version: "3.7.3",
  },
  {
    id: "user",
    name: "User",
    category: "other",
    unicode: "e66a",
    version: "3.7.3",
  },
  {
    id: "video-camera",
    name: "Video Camera",
    category: "other",
    unicode: "e66b",
    version: "3.7.3",
  },
  {
    id: "home",
    name: "Home",
    category: "other",
    unicode: "e65e",
    version: "3.7.3",
  },
  {
    id: "loading",
    name: "Loading",
    category: "other",
    unicode: "e64d",
    version: "3.7.3",
  },
  {
    id: "loading-3-quarters",
    name: "Loading 3 Quarters",
    category: "other",
    unicode: "e6ae",
    version: "3.7.3",
  },
  {
    id: "cloud-upload-o",
    name: "Cloud Upload Outlined",
    category: "other",
    unicode: "e684",
    version: "3.7.3",
  },
  {
    id: "cloud-download-o",
    name: "Cloud Download Outlined",
    category: "other",
    unicode: "e683",
    version: "3.7.3",
  },
  {
    id: "cloud-upload",
    name: "Cloud Upload",
    category: "other",
    unicode: "e681",
    version: "3.7.3",
  },
  {
    id: "cloud-o",
    name: "Cloud Outlined",
    category: "other",
    unicode: "e67f",
    version: "3.7.3",
  },
  {
    id: "star-o",
    name: "Star Outlined",
    category: "other",
    unicode: "e661",
    version: "3.7.3",
  },
  {
    id: "star",
    name: "Star",
    category: "other",
    unicode: "e660",
    version: "3.7.3",
  },
  {
    id: "heart-o",
    name: "Heart Outlined",
    category: "other",
    unicode: "e6a4",
    version: "3.7.3",
  },
  {
    id: "heart",
    name: "Heart",
    category: "other",
    unicode: "e6a3",
    version: "3.7.3",
  },
  {
    id: "environment",
    name: "Environment",
    category: "other",
    unicode: "e685",
    version: "3.7.3",
  },
  {
    id: "environment-o",
    name: "Environment Outlined",
    category: "other",
    unicode: "e686",
    version: "3.7.3",
  },
  {
    id: "eye",
    name: "Eye",
    category: "other",
    unicode: "e687",
    version: "3.7.3",
  },
  {
    id: "eye-o",
    name: "Eye Outlined",
    category: "other",
    unicode: "e688",
    version: "3.7.3",
  },
  {
    id: "camera",
    name: "Camera",
    category: "other",
    unicode: "e689",
    version: "3.7.3",
  },
  {
    id: "camera-o",
    name: "Camera Outlined",
    category: "other",
    unicode: "e68a",
    version: "3.7.3",
  },
  {
    id: "save",
    name: "Save",
    category: "other",
    unicode: "e669",
    version: "3.7.3",
  },
  {
    id: "team",
    name: "Team",
    category: "other",
    unicode: "e66d",
    version: "3.7.3",
  },
  {
    id: "solution",
    name: "Solution",
    category: "other",
    unicode: "e66f",
    version: "3.7.3",
  },
  {
    id: "phone",
    name: "Phone",
    category: "other",
    unicode: "e675",
    version: "3.7.3",
  },
  {
    id: "filter",
    name: "Filter",
    category: "other",
    unicode: "e663",
    version: "3.7.3",
  },
  {
    id: "exception",
    name: "Exception",
    category: "other",
    unicode: "e665",
    version: "3.7.3",
  },
  {
    id: "export",
    name: "Export",
    category: "other",
    unicode: "e691",
    version: "3.7.3",
  },
  {
    id: "customer-service",
    name: "Customer Service",
    category: "other",
    unicode: "e634",
    version: "3.7.3",
  },
  {
    id: "qrcode",
    name: "QR Code",
    category: "other",
    unicode: "e67c",
    version: "3.7.3",
  },
  {
    id: "scan",
    name: "Scan",
    category: "other",
    unicode: "e697",
    version: "3.7.3",
  },
  {
    id: "like",
    name: "Like",
    category: "other",
    unicode: "e64c",
    version: "3.7.3",
  },
  {
    id: "like-o",
    name: "Like Outlined",
    category: "other",
    unicode: "e69d",
    version: "3.7.3",
  },
  {
    id: "dislike",
    name: "Dislike",
    category: "other",
    unicode: "e64b",
    version: "3.7.3",
  },
  {
    id: "dislike-o",
    name: "Dislike Outlined",
    category: "other",
    unicode: "e69e",
    version: "3.7.3",
  },
  {
    id: "message",
    name: "Message",
    category: "other",
    unicode: "e6ab",
    version: "3.7.3",
  },
  {
    id: "pay-circle",
    name: "Pay Circle",
    category: "other",
    unicode: "e6a5",
    version: "3.7.3",
  },
  {
    id: "pay-circle-o",
    name: "Pay Circle Outlined",
    category: "other",
    unicode: "e6a6",
    version: "3.7.3",
  },
  {
    id: "calculator",
    name: "Calculator",
    category: "other",
    unicode: "e6aa",
    version: "3.7.3",
  },
  {
    id: "pushpin",
    name: "Pushpin",
    category: "other",
    unicode: "e6a2",
    version: "3.7.3",
  },
  {
    id: "pushpin-o",
    name: "Pushpin Outlined",
    category: "other",
    unicode: "e6a1",
    version: "3.7.3",
  },
  {
    id: "bulb",
    name: "Bulb",
    category: "other",
    unicode: "e649",
    version: "3.7.3",
  },
  {
    id: "select",
    name: "Select",
    category: "other",
    unicode: "e64a",
    version: "3.7.3",
  },
  {
    id: "switcher",
    name: "Switcher",
    category: "other",
    unicode: "e913",
    version: "3.7.3",
  },
  {
    id: "rocket",
    name: "Rocket",
    category: "other",
    unicode: "e90f",
    version: "3.7.3",
  },
  {
    id: "bell",
    name: "Bell",
    category: "other",
    unicode: "e64e",
    version: "3.7.3",
  },
  {
    id: "disconnect",
    name: "Disconnect",
    category: "other",
    unicode: "e64f",
    version: "3.7.3",
  },
  {
    id: "database",
    name: "Database",
    category: "other",
    unicode: "e650",
    version: "3.7.3",
  },
  {
    id: "compass",
    name: "Compass",
    category: "other",
    unicode: "e6db",
    version: "3.7.3",
  },
  {
    id: "barcode",
    name: "Barcode",
    category: "other",
    unicode: "e652",
    version: "3.7.3",
  },
  {
    id: "hourglass",
    name: "Hourglass",
    category: "other",
    unicode: "e653",
    version: "3.7.3",
  },
  {
    id: "key",
    name: "Key",
    category: "other",
    unicode: "e654",
    version: "3.7.3",
  },
  {
    id: "flag",
    name: "Flag",
    category: "other",
    unicode: "e655",
    version: "3.7.3",
  },
  {
    id: "layout",
    name: "Layout",
    category: "other",
    unicode: "e656",
    version: "3.7.3",
  },
  {
    id: "printer",
    name: "Printer",
    category: "other",
    unicode: "e673",
    version: "3.7.3",
  },
  {
    id: "sound",
    name: "Sound",
    category: "other",
    unicode: "e6e9",
    version: "3.7.3",
  },
  {
    id: "usb",
    name: "USB",
    category: "other",
    unicode: "e6d7",
    version: "3.7.3",
  },
  {
    id: "skin",
    name: "Skin",
    category: "other",
    unicode: "e6d8",
    version: "3.7.3",
  },
  {
    id: "tool",
    name: "Tool",
    category: "other",
    unicode: "e6d9",
    version: "3.7.3",
  },
  {
    id: "sync",
    name: "Sync",
    category: "other",
    unicode: "e6da",
    version: "3.7.3",
  },
  {
    id: "wifi",
    name: "Wi-Fi",
    category: "other",
    unicode: "e6d6",
    version: "3.7.3",
  },
  {
    id: "car",
    name: "Car",
    category: "other",
    unicode: "e6dc",
    version: "3.7.3",
  },
  {
    id: "schedule",
    name: "Schedule",
    category: "other",
    unicode: "e6df",
    version: "3.7.3",
  },
  {
    id: "user-add",
    name: "User Add",
    category: "other",
    unicode: "e6ed",
    version: "3.7.3",
  },
  {
    id: "user-delete",
    name: "User Delete",
    category: "other",
    unicode: "e6e0",
    version: "3.7.3",
  },
  {
    id: "usergroup-add",
    name: "Usergroup Add",
    category: "other",
    unicode: "e6dd",
    version: "3.7.3",
  },
  {
    id: "usergroup-delete",
    name: "Usergroup Delete",
    category: "other",
    unicode: "e6e1",
    version: "3.7.3",
  },
  {
    id: "man",
    name: "Man",
    category: "other",
    unicode: "e6e2",
    version: "3.7.3",
  },
  {
    id: "woman",
    name: "Woman",
    category: "other",
    unicode: "e6ec",
    version: "3.7.3",
  },
  {
    id: "shop",
    name: "Shop",
    category: "other",
    unicode: "e6e3",
    version: "3.7.3",
  },
  {
    id: "gift",
    name: "Gift",
    category: "other",
    unicode: "e6e4",
    version: "3.7.3",
  },
  {
    id: "idcard",
    name: "ID Card",
    category: "other",
    unicode: "e6e5",
    version: "3.7.3",
  },
  {
    id: "medicine-box",
    name: "Medicine Box",
    category: "other",
    unicode: "e6e6",
    version: "3.7.3",
  },
  {
    id: "red-envelope",
    name: "Red Envelope",
    category: "other",
    unicode: "e6e7",
    version: "3.7.3",
  },
  {
    id: "coffee",
    name: "Coffee",
    category: "other",
    unicode: "e6e8",
    version: "3.7.3",
  },
  {
    id: "copyright",
    name: "Copyright",
    category: "other",
    unicode: "e6de",
    version: "3.7.3",
  },
  {
    id: "trademark",
    name: "Trademark",
    category: "other",
    unicode: "e651",
    version: "3.7.3",
  },
  {
    id: "safety",
    name: "Safety",
    category: "other",
    unicode: "e6ea",
    version: "3.7.3",
  },
  {
    id: "wallet",
    name: "Wallet",
    category: "other",
    unicode: "e6eb",
    version: "3.7.3",
  },
  {
    id: "bank",
    name: "Bank",
    category: "other",
    unicode: "e6ee",
    version: "3.7.3",
  },
  {
    id: "trophy",
    name: "Trophy",
    category: "other",
    unicode: "e6ef",
    version: "3.7.3",
  },
  {
    id: "contacts",
    name: "Contacts",
    category: "other",
    unicode: "e6f0",
    version: "3.7.3",
  },
  {
    id: "global",
    name: "Global",
    category: "other",
    unicode: "e6f1",
    version: "3.7.3",
  },
  {
    id: "shake",
    name: "Shake",
    category: "other",
    unicode: "e94f",
    version: "3.7.3",
  },
  {
    id: "api",
    name: "API",
    category: "other",
    unicode: "e951",
    version: "3.7.3",
  },
  {
    id: "fork",
    name: "Fork",
    category: "other",
    unicode: "e6f2",
    version: "3.7.3",
  },
  {
    id: "dashboard",
    name: "Dashboard",
    category: "other",
    unicode: "e99a",
    version: "3.7.3",
  },
  {
    id: "form",
    name: "Form",
    category: "other",
    unicode: "e996",
    version: "3.7.3",
  },
  {
    id: "table",
    name: "Table",
    category: "other",
    unicode: "e998",
    version: "3.7.3",
  },
  {
    id: "profile",
    name: "Profile",
    category: "other",
    unicode: "e999",
    version: "3.7.3",
  },
];
